version: "3"
services:
  fluentd:
    container_name: fluentd
    user: root
    build:
      context: .
    image: fluentd
    volumes:
    - /var/lib/docker/containers:/fluentd/log/containers
    - ./fluent.conf:/fluentd/etc/fluent.conf
    - ./logs:/output/
    logging:
      driver: "local"
  elasticsearch: # port 9200
    image: elasticsearch:8.3.2
    container_name: elasticsearch
    environment:
    - node.name=elasticsearch
    - cluster.initial_master_nodes=elasticsearch
    - bootstrap.memory_lock=true
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
  kibana:
    image: kibana:8.3.2
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200