version: '2'

services:
  rancher:
    image: rancher/rancher:latest
    restart: always
    # ports:
    # - "80:80/tcp"
    # - "443:443/tcp"
    volumes:
    - /mnt/gfs1/docker/rancher:/var/lib/rancher"
    privileged: true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rancher.entrypoints=http"
      - "traefik.http.routers.rancher.rule=Host(`rancher.crowlight.com`)"
      - "traefik.http.routers.rancher-secure.entrypoints=https"
      - "traefik.http.routers.rancher-secure.rule=Host(`rancher.crowlight.com`)"
      - "traefik.http.routers.rancher-secure.tls=true"
      - "traefik.http.routers.rancher-secure.service=rancher"
      - "traefik.http.services.rancher.loadbalancer.server.port=80"
      - "traefik.http.services.rancher.loadbalancer.server.scheme=http"
      - "traefik.docker.network=traefik_traffic"

volumes:
  rancher-data:
