---
version: "3.7"
services:
  heimdall:
    image: lscr.io/linuxserver/heimdall
    restart: always
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
      - TEST_MOOSE=True
    volumes:
      - /home/moose/containers/heimdall:/config
    networks:
      - traefik_traffic
    dns: 10.1.2.120
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.heimdall.entrypoints=http"
      - "traefik.http.routers.heimdall.rule=Host(`home.crowlight.com`)"
      - "traefik.http.routers.heimdall-secure.entrypoints=https"
      - "traefik.http.routers.heimdall-secure.rule=Host(`home.crowlight.com`)"
      - "traefik.http.routers.heimdall-secure.tls=true"
      - "traefik.http.routers.heimdall-secure.service=heimdall"
      - "traefik.http.services.heimdall.loadbalancer.server.port=443"
      - "traefik.http.services.heimdall.loadbalancer.server.scheme=https"
      - "traefik.docker.network=traefik_traffic"

networks:
  traefik_traffic:
    external: true
