version: "3.8"
services:
  prometheus:
    image: prom/prometheus
    user: root
    ports:
      - target: 9090
        published: 7070
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/gfs/docker/prometheus:/prometheus
    configs:
      - source: prometheus-v2
        target: /etc/prometheus/prometheus.yml
    deploy:
      replicas: 1
  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    volumes:
      - /mnt/gfs/docker/grafana:/var/lib/grafana
  cadvisor:
    image: gcr.io/google-containers/cadvisor
    command: -docker_only
    ports:
      - target: 8080
        published: 7071
        mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/rootfs:ro
      - /var/run:/var/run
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
    deploy:
      mode: global
      labels:
        prometheus-job: "cadvisor"

configs:
  prometheus-v2:
    external: true
