version: "3.7"
services:
  sonarr:
    image: ghcr.io/linuxserver/sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
    volumes:
      - /mnt/gfs1/docker/sonarr/config:/config
      - /nfs/media/tv:/tv
      - /nfs/lab/media:/downloads
    ports:
      - 8989:8989
    #labels:
    #  - "traefik.enable=true"
    #  - "traefik.http.routers.sonarr.entrypoints=http"
    #  - "traefik.http.routers.sonarr.rule=Host(`sonarr.crowlight.com`)"
    #  - "traefik.http.middlewares.sonarr-https-redirect.redirectscheme.scheme=https"
    #  - "traefik.http.routers.sonarr.middlewares=sonarr-https-redirect"
    #  - "traefik.http.routers.sonarr-secure.entrypoints=https"
    #  - "traefik.http.routers.sonarr-secure.rule=Host(`sonarr.crowlight.com`)"
    #  - "traefik.http.routers.sonarr-secure.tls=true"
    #  - "traefik.http.routers.sonarr-secure.service=sonarr"
    #  - "traefik.http.services.sonarr.loadbalancer.server.port=8989"
    #  - "traefik.docker.network=traefik-network_public"
    
  radarr:
    image: ghcr.io/linuxserver/radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
    volumes:
      - /mnt/gfs1/docker/radarr/config:/config
      - /nfs/media/movies:/movies
      - /nfs/lab/media:/downloads
    ports:
      - 7878:7878
    #labels:
    #  - "traefik.enable=true"
    #  - "traefik.http.routers.radarr.entrypoints=http"
    #  - "traefik.http.routers.radarr.rule=Host(`radarr.crowlight.com`)"
    #  - "traefik.http.middlewares.radarr-https-redirect.redirectscheme.scheme=https"
    #  - "traefik.http.routers.radarr.middlewares=radarr-https-redirect"
    #  - "traefik.http.routers.radarr-secure.entrypoints=https"
    #  - "traefik.http.routers.radarr-secure.rule=Host(`radarr.crowlight.com`)"
    #  - "traefik.http.routers.radarr-secure.tls=true"
    #  - "traefik.http.routers.radarr-secure.service=radarr"
    #  - "traefik.http.services.radarr.loadbalancer.server.port=7878"
    #  - "traefik.docker.network=traefik-network_public"
    
  jackett:
    image: ghcr.io/linuxserver/jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /mnt/gfs1/docker/jackett/config:/config
      - /nfs/lab/media:/downloads
    ports:
      - 9117:9117
    #labels:
    #  - "traefik.enable=true"
    #  - "traefik.http.routers.jackett.entrypoints=http"
    #  - "traefik.http.routers.jackett.rule=Host(`jackett.crowlight.com`)"
    #  - "traefik.http.middlewares.jackett-https-redirect.redirectscheme.scheme=https"
    #  - "traefik.http.routers.jackett.middlewares=jackett-https-redirect"
    #  - "traefik.http.routers.jackett-secure.entrypoints=https"
    #  - "traefik.http.routers.jackett-secure.rule=Host(`jackett.crowlight.com`)"
    #  - "traefik.http.routers.jackett-secure.tls=true"
    #  - "traefik.http.routers.jackett-secure.service=jackett"
    #  - "traefik.http.services.jackett.loadbalancer.server.port=7878"
    #  - "traefik.docker.network=traefik-network_public"
    
  sabnzbd:
    image: ghcr.io/linuxserver/sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
    volumes:
      - /mnt/gfs1/docker/nzb/config:/config
      - /nfs/lab/media:/downloads
      - /nfs/lab/media/nzb/incomplete:/incomplete-downloads #optional
    ports:
      - 9080:8080
      - 9090:9090
    #labels:
    #  - "traefik.enable=true"
    #  - "traefik.http.routers.nzb.entrypoints=http"
    #  - "traefik.http.routers.nzb.rule=Host(`nzb.crowlight.com`)"
    #  - "traefik.http.middlewares.nzb-https-redirect.redirectscheme.scheme=https"
    #  - "traefik.http.routers.nzb.middlewares=nzb-https-redirect"
    #  - "traefik.http.routers.nzb-secure.entrypoints=https"
    #  - "traefik.http.routers.nzb-secure.rule=Host(`nzb.crowlight.com`)"
    #  - "traefik.http.routers.nzb-secure.tls=true"
    #  - "traefik.http.routers.nzb-secure.service=nzb"
    #  - "traefik.http.services.nzb.loadbalancer.server.port=7878"
    #  - "traefik.docker.network=traefik-network_public"
  ombi:
    image: lscr.io/linuxserver/ombi
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
      #- BASE_URL=/ombi #optional
    volumes:
      - /mnt/gfs1/docker/ombi:/config
    ports:
      - 3579:3579
    #labels:
    #  - "traefik.enable=true"
    #  - "traefik.http.routers.ombi.entrypoints=http"
    #  - "traefik.http.routers.ombi.rule=Host(`add.crowlight.com`)"
    #  - "traefik.http.middlewares.ombi-https-redirect.redirectscheme.scheme=https"
    #  - "traefik.http.routers.ombi.middlewares=default-headers@file,ombi-https-redirect"
    #  - "traefik.http.routers.ombi-secure.entrypoints=https"
    #  - "traefik.http.routers.ombi-secure.rule=Host(`add.crowlight.com`)"
    #  - "traefik.http.routers.ombi-secure.tls=true"
    #  - "traefik.http.routers.ombi-secure.middlewares=default-headers@file"
    #  - "traefik.http.routers.ombi-secure.service=ombi"
    #  - "traefik.http.services.ombi.loadbalancer.server.port=3579"
    #  - "traefik.docker.network=traefik-network_public"