---
version: "3.7"
services:
  portainer:
    image: portainer/portainer-ce:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/gfs1/docker/portainer:/data
    networks:
      - traefik_traffic
    ports:
      - 9443:9443
      - 8000:8000
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.entrypoints=http"
      - "traefik.http.routers.portainer.rule=Host(`portainer.crowlight.com`)"
      #- "traefik.http.middlewares.portainer-https-redirect.redirectscheme.scheme=https"
      #- "traefik.http.routers.portainer.middlewares=portainer-https-redirect"
      - "traefik.http.routers.portainer-secure.entrypoints=https"
      - "traefik.http.routers.portainer-secure.rule=Host(`portainer.crowlight.com`)"
      - "traefik.http.routers.portainer-secure.tls=true"
      - "traefik.http.routers.portainer-secure.service=portainer"
      - "traefik.http.services.portainer.loadbalancer.server.port=9443"
      - "traefik.http.services.portainer.loadbalancer.server.scheme=https"
      - "traefik.docker.network=traefik_traffic"

networks:
  traefik_traffic:
    external: true
