version: "3.7"
services:
  deluge:
    image: lscr.io/linuxserver/deluge
    container_name: deluge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
      - DELUGE_LOGLEVEL=error #optional
    network_mode: "service:gluetun"
    volumes:
      - /mnt/gfs1/docker/deluge:/config
      - /nfs/lab/media:/downloads
    #ports:
    #  - 8112:8112
    #  - 6881:6881
    #  - 6881:6881/udp
    restart: always
    #labels:
    #  - "traefik.enable=true"
    #  - "traefik.http.routers.sonarr.entrypoints=http"
    #  - "traefik.http.routers.sonarr.rule=Host(`deluge.crowlight.com`)"
    #  - "traefik.http.middlewares.sonarr-https-redirect.redirectscheme.scheme=https"
    #  - "traefik.http.routers.sonarr.middlewares=sonarr-https-redirect"
    #  - "traefik.http.routers.sonarr-secure.entrypoints=https"
    #  - "traefik.http.routers.sonarr-secure.rule=Host(`deluge.crowlight.com`)"
    #  - "traefik.http.routers.sonarr-secure.tls=true"
    #  - "traefik.http.routers.sonarr-secure.service=sonarr"
    #  - "traefik.http.services.sonarr.loadbalancer.server.port=8112"
    #  - "traefik.docker.network=traefik_traffic"
    
  jackett:
    image: ghcr.io/linuxserver/jackett
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /mnt/gfs1/docker/jackett/config:/config
      - /nfs/lab/media:/downloads
    network_mode: "service:gluetun"
    #ports:
    #  - 9117:9117
    #networks:
    #  - traefik_traffic
    #labels:
    #  - "traefik.enable=true"
    #  - "traefik.http.routers.jackett.entrypoints=http"
    #  - "traefik.http.routers.jackett.rule=Host(`jackett.crowlight.com`)"
    #  - "traefik.http.middlewares.jackett-https-redirect.redirectscheme.scheme=https"
    #  - "traefik.http.routers.jackett.middlewares=jackett-https-redirect"
    #  - "traefik.http.routers.jackett-secure.entrypoints=https"
    #  - "traefik.http.routers.jackett-secure.rule=Host(`jackett.crowlight.com`)"
    #  - "traefik.http.routers.jackett-secure.tls=true"
    #  - "traefik.http.routers.jackett-secure.service=jackett"
    #  - "traefik.http.services.jackett.loadbalancer.server.port=9117"
    #  - "traefik.docker.network=traefik_traffic"
      
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    restart: always
    #network: traefik_traffic
    cap_add:
      - NET_ADMIN
    ports:
      - 9999:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 8112:8112 # Below are pass through to deluge
      - 6881:6881
      - 6881:6881/udp
      - 9117:9117 # Pass through to Jackett
    volumes:
      - /mnt/gfs1/docker/gluetun:/gluetun
    env_file:
      - ~/configs/docker/torrent.env
      
#networks:
#  traefik_traffic:
#    external: true